blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://shopify.github.io/react-native-performance/
    about: Read the official documentation.
  - name: Feature proposals
    url: https://github.com/Shopify/react-native-performance/discussions
    about: Post a feature proposal on Discussions.
  - name: Discussions
    url: https://github.com/Shopify/react-native-performance/discussions
    about: Discuss questions, ideas etc. and share resources related to the library.
  - name: Shopify React Native Open Source Discord
    url: https://discord.com/channels/928252803867107358/928253059375726622
    about: Chat with other community members in the react-native-performance channel on Shopify React Native Open Source Discord.
