name: Conventional Commits Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
      - name: Setup NodeJS and NPM
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16.13.2
      - name: Add @commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Lint PR and commits
        env:
          TITLE: ${{ github.event.pull_request.title }}
          COMMITS: ${{ github.event.pull_request.commits }}
        run: bin/conventional-commits.sh "$TITLE" $COMMITS
