name: Conventional Commits Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
        with:
          fetch-depth: 0
      - name: Setup NodeJS and NPM
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 16.13.2
      - name: Add @commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Lint PR and commits
        env:
          TITLE: ${{ github.event.pull_request.title }}
          COMMITS: ${{ github.event.pull_request.commits }}
        run: bin/conventional-commits.sh "$TITLE" $COMMITS
